- id: doi:10.1098/rspb.2023.1290
  type: paper
  image: https://royalsocietypublishing.org/cms/asset/8e76a7b3-bb8d-4b65-8fe3-c8d226edd427/rspb20231290f01.jpg
  tags:
    - biodiversity

- id: doi:10.1007/s10021-023-00874-w
  type: paper
  image: images/pubs/ecos24.png
  tags:
    - biodiversity

- id: doi:10.1111/nph.18856
  type: paper
  image: https://nph.onlinelibrary.wiley.com/cms/asset/3fbbe1a1-0cfc-41d3-8e3e-5b37bd2efc56/nph18856-fig-0001-m.jpg
  tags:
    - lightning
    - mortality

- id: doi:10.1038/s41477-022-01230-x
  type: paper
  image: images/pubs/natPlants22.png
  tags: 
    - mortality
    - lightning

- id: doi:10.1002/ecy.3541
  type: paper
  image: https://esajournals.onlinelibrary.wiley.com/cms/asset/8a1f7884-9c5c-4b8d-bf7e-6bc8c563425e/ecy3541-fig-0001-m.jpg
  tags: 
    - mortality
    - lightning 
    - biodiversity

- id: doi:10.1038/s41477-021-00879-0
  type: paper
  image: images/pubs/natPlants21.png
  tags: 
    - mortality
    - lightning

- id: doi:10.1111/gcb.15227
  type: paper
  image: https://onlinelibrary.wiley.com/cms/asset/3b7f0f24-b127-404d-ac17-82560875f5d4/gcb15227-fig-0001-m.jpg
  tags: 
    - mortality
    - lightning
    - biodiversity
    - conservation

- id: doi:10.1111/1365-2745.13404
  type: paper
  description: Harper Prize finalist for best paper by an early career scientist
  image: https://besjournals.onlinelibrary.wiley.com/cms/asset/787dcfc8-ac06-4bd8-803d-60ae601ca0aa/jec13404-fig-0004-m.jpg
  tags: 
    - lightning

- id: doi:10.1111/btp.12826
  type: paper
  image: https://onlinelibrary.wiley.com/cms/asset/5ff5c89b-bf2f-4824-8d3d-40afce21bfae/btp12826-fig-0001-m.jpg
  tags: 
    - lightning
    - mortality

- id: doi:10.1093/aesa/saaa015
  type: paper
  image: https://bioone.org/ContentImages/Journals/esaa/113/6/saaa015/graphic/WebImages/img-z3-9_447.jpg
  tags: 
    - lightning
    - deadwood
    - biodiversity

- id: doi:10.1111/nph.16260
  type: paper
  image: https://nph.onlinelibrary.wiley.com/cms/asset/1b388a7e-5f91-4f81-bce8-6c60829b1b8a/nph16260-fig-0001-m.jpg
  tags: 
    - lightning
    - mortality
    - biodiversity

- id: doi:10.1098/rspb.2019.1536
  type: paper
  image: https://royalsocietypublishing.org/cms/asset/afff0628-fa14-4b79-bb57-b820eb057497/rspb20191536f03.jpg
  tags: 
    - deadwood

- id: doi:10.1111/1365-2435.13440
  type: paper
  image: https://besjournals.onlinelibrary.wiley.com/cms/asset/2c340b44-e183-44c0-ad7d-d1734dbabebd/fec13440-fig-0002-m.jpg
  tags: 
    - deadwood

- id: doi:10.1111/btp.12709
  type: paper
  image: https://onlinelibrary.wiley.com/cms/asset/fea0bb55-8b84-4ed4-9b5f-6f7baf6575b3/btp12709-fig-0002-m.jpg
  tags: 
    - biodiversity

- id: doi:10.1007/s10021-019-00359-9
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs10021-019-00359-9/MediaObjects/10021_2019_359_Fig5_HTML.png
  tags: 
    - biodiversity
    - deadwood

- id: doi:10.1007/s10021-019-00341-5
  type: paper
  image: images/pubs/ecos19.png
  tags: 
    - deadwood

- id: doi:10.1093/aesa/say026
  type: paper
  image: https://bioone.org/ContentImages/Journals/esaa/111/6/say026/graphic/WebImages/t04_319.gif
  tags: 
    - biodiversity

- id: doi:10.1111/1365-2435.13047
  type: paper
  image: https://besjournals.onlinelibrary.wiley.com/cms/asset/06b8d0ac-5ae0-4fff-8332-7c265ca85b9e/fec13047-fig-0001-m.jpg
  tags: 
    - decomposition

- id: doi:10.1002/ece3.3347
  type: paper
  image: https://onlinelibrary.wiley.com/cms/asset/dc5e84f4-72bf-47b1-84db-71f48f82416c/ece33347-fig-0006-m.jpg
  tags: 
    - lightning

- id: doi:10.1111/cobi.12949
  type: paper
  image: 
  tags: 
    - conservation

- id: doi:10.1002/ece3.3095
  type: paper
  image: https://onlinelibrary.wiley.com/cms/asset/9e2c8daf-f138-4811-9217-6937fd1f3944/ece33095-fig-0009-m.jpg
  tags: 
    - lightning
    - mortality

- id: doi:10.25849/myrmecol.news_023:033
  type: paper
  image: 
  tags: 
    - biodiversity

- id: doi:10.1139/cjfr-2014-0380
  type: paper
  image: https://cdnsciencepub.com/cms/10.1139/cjfr-2014-0380/asset/images/large/cjfr-2014-0380f1.jpeg
  tags: 
    - biodiversity
    - lightning

- id: doi:10.1139/cjfr-2015-0081
  type: paper
  image: https://cdnsciencepub.com/cms/10.1139/cjfr-2015-0081/asset/images/large/cjfr-2015-0081f5.jpeg
  tags: 
    - lightning

- id: doi:10.3159/TORREY-D-13-00066.1
  type: paper
  image: images/pubs/torrey14.jpeg
  tags: 
    - deadwood